# Generated by Django 4.2.4 on 2023-09-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_tg_chat_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRoles',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('owner', 'owner'), ('admin', 'admin')], max_length=20, null=True),
        ),
    ]
